### ISSUE TITLE
Error getting p in assignment_setup?

### ISSUE THREAD

**Issue by johnkanji** [dilevin/CSC2549-a5-rigid-bodies#1]
In assignment_setup.h the code gets a segment of length 9 and assigns it to the 3d vector p. Should this not be of length 3?

https://github.com/dilevin/CSC2549-a5-rigid-bodies/blob/bb3653e4d151d34ec176af5a187ea00522e73521/assignment_setup.h#L51

**Comment by dilevin** [comment]
It should be 3, correct.

**Comment by dilevin** [comment]
and it's fixed in the code now.
