### ISSUE TITLE
Slight confusion about the omega passed into rodrigues

### ISSUE THREAD

**Issue by EDToaster** [dilevin/CSC2549-a5-rigid-bodies#6]
Seems like Rodrigues doesn't take in a `double dt` parameter despite the angle of rotation `theta` being dependent on `dt` in both the [lecture notes](https://youtu.be/1RF7j-Yc21c?t=959) and the [wiki page](https://en.wikipedia.org/wiki/Rodrigues%27_rotation_formula). Passing in `dt * omega` to rodrigues seems like a very hacky way to do it. 

Maybe this is something that could be clarified for next year's offering

**Comment by dilevin** [comment]
Remember that Rodrigues’ rotation formula doesn’t know that the angle is coming from a dynamic equation, it only knows that it requires an angle as input. Hence why we pass the angle and not omega and a separate time variable.

I’d argue this isn’t hacky but rather implementing the formula as it is intended.
